### ISSUE TITLE
Improve recipe show page

### ISSUE THREAD

**Issue by kieranklaassen** [freesewing/freesewing.org#377]
- [x] Change copy of buttons
- [x] Move Update button to title and description (maybe inline editing?
- [x] Make an Edit button that lets you edit the recipe for real, instead of recreating it
- [x] Make sure when saving/overwriting the recipe we give a big warning
- [ ] Add a model name below recipe name
- [x] Add Recipe to buttons: `Duplicate Recipe` and `Edit Recipe` to make it clear it's not called a pattern, but a recipe

<img width="931" alt="muslin-v1" src="https://user-images.githubusercontent.com/209089/70162351-207fe180-1683-11ea-8b12-5b1db4f98b1a.png">

**Comment by joostdecock** [comment]
![Screenshot_2020-03-08 Breanna voor Stéphanie](https://user-images.githubusercontent.com/1708494/76167678-c81c1c80-6168-11ea-80e7-607c6b66ea8e.png)

**Comment by joostdecock** [comment]
I've ticked almost all the boxes :laughing:  Allow me to explain:

 - Change copy of buttons: The buttons are now just icons. But if you click the 'Show details' button, you get the same, but with info
 - Move Update button to title and description (maybe inline editing?: There's a 'update notes' button that lets you do this. It's not in this screenshot, but it is when you edit a pattern
 - Make an Edit button that lets you edit the recipe for real, instead of recreating it: Thank you for what seems like an obvious thing, but I didn't really think about that somehow. Now you can, that pencil icon does exactly that. It also uses a URL that *makes sense* so if you are on `/patterns/abcde/` then the *edit* button brings you to `/patterns/abcde/edit` where you can edit your pattern. You can also bootstrap the SPA on that link, it will work too.
 - Make sure when saving/overwriting the recipe we give a big warning: We now have `save` and `saveAs`, they do different things.
 - Add Recipe to buttons: Duplicate Recipe and Edit Recipe to make it clear it's not called a pattern, but a recipe: Except that nowadays, it's called a pattern :)

I am (still) not in love with how the page looks, but from a functionality point of view, I think it makes more sense. 

But I think that at least some of the pain-points you highlighted have been addressed. Or at least I tried ;)

**Comment by joostdecock** [comment]
Stale/implemented. Closing
