### ISSUE TITLE
Rename Recipes to My Patterns

### ISSUE THREAD

**Issue by kieranklaassen** [freesewing/freesewing.org#378]
I'm a bit confused about the naming around patterns and recipes. I get their working. 

But if you want to create a new pattern, you get a recipe.

Should be call recipes My Patterns?
Or should we say: Create New Recipe, instead of pattern?

Or maybe I miss something completely. Please advice :)

<img width="390" alt="Choose_a_model" src="https://user-images.githubusercontent.com/209089/70163561-4efebc00-1685-11ea-8c42-881b7f3aba91.png">

**Comment by joostdecock** [comment]
Yeah, I think this one is on me :)

Recipes are new since v2.0, and they were an attempt to have a more consistent terminology. An attempt that clearly wasn't perfect :)

Prior to v2, we used:

 - **pattern**: Something like *brian* or *simon*
 - **draft**: What our users call a pattern. The thing that you actually end up printing
 - **draft**: A method in core, that... you know, drafts a pattern

So there's different terms that mean the same thing, or the same term that mean different things, based on context.

In v1, we stored *drafts* in the database (we stored the entire SVG output). 
In v2, we don't do that, and store what (inside the codebase) is called a *gist*. But because users don't know what the heck a gist is, I've named this a *recipe*. 

I also tried to rename a few other things to clarify which is which. So in v2 we have:

 - **design**: Something like *brian* or *simon* should be referred to as a design, but it's typically referred to as a pattern because that's what people google for
 - **pattern**: What our users call a pattern. The thing that you actually end up printing
 - **draft**: We still have that method in core, but it should no longer used in user-facing things
 - **recipe**: The user-friendly name for a *gist*, which is the JSON data required to recreate the pattern

I think one way to address the ambiguity is to change **Patterns** in the website to **Designs**, and use **Pattern** as the new **Recipe**. This does however have some knock-on effects:

 - The URLs are all like `freesewing.org/patterns/brian` or freesewing.org/docs/patterns/brian` and this would break that
 - People google `free sewing patterns` all the time, which is very close to `freesewing patterns`. But nobody is googling `free sewing designs` so it would be bad for SEO

Because this would be a rather disruptive change to the URL structure, it might be best to get some input on this and come to a broad(er) consensus on what kind of names actually make sense to people. (there's also the i18n angle here).

Perhaps for issues like this, we can setup an RFC repo. Gatsby [has one](https://github.com/gatsbyjs/rfcs) and it's essentially just a repo where you write an RFC, submit it as a PR, and then world+dog can comment on it until a consensus (hopefully) emerges.

This could be our first RFC, where we outline the issue of conflicting terminology, and ask people what they think would make most sense.

In general, I always feel like it is good to get people involved. The flip side of that coin is that you often end up spending a lot of time and effort setting these things up, only to realize that nobody cares.
That can be a rather soul-crushing experience, so I'm sometimes a bit reluctant to go down that road. However, in this case, I think the bar is rather low for participation. No technical skills are required for an opinion on this matter, and we could solicit input in our yearly blog post which I should write this weekend.

But hey, I also don't want to hijack this issue, so tell me what you think.

**Comment by kieranklaassen** [comment]
I completely agree with you. I think, however, this could be a little bit easier then what you propose. My point is view is purely from a UX workflow and from that point of view I would like to propose:

1. Rename `Recipes` to `My Patterns` in the menu only
2. If you are logged in, rename Patterns in the menu to My Patterns so you can access yours quickly too
3. Remove the word, `Recipe` from consumer-facing places, but keep it in the URL and backend
4. Do not change anything in the name Pattern now

This would be a very easy fix and clarify a lot in day to day use of Freesewing.

**Comment by kieranklaassen** [comment]
```
 I can see the (potential) confusion with these names. This is probably the first time I'm actually looking at these parts on the site.
To me a Pattern is the description/definition of a garment. So a Pattern as we're using the term on the site makes sense to me.
A Recipe is something that describes a food product. I know that you can use it for chemical processes, medical drugs, etc. Or in the way of a recipe for success. But that is not what comes to mind when I see the term on a site like this (caveat: English as second language, 25 years).
Now I'm not sure what term we should use for a personal derivative of a generic Pattern.
My Pattern makes sense to me```

**Comment by joostdecock** [comment]
> Rename **Recipes** to **My Patterns** in the menu only
> If you are logged in, rename **Patterns** in the menu to **My Patterns** so you can access yours quickly too

Wouldn't this mean we end up with **My patterns** twice?

**Comment by joostdecock** [comment]
Renaming things has been done in 2.2. Closing this for now. We can re-evaluate this down the road.
