### ISSUE TITLE
Thank-you page after patron signup is missing

### ISSUE THREAD

**Issue by kieranklaassen** [freesewing/freesewing.org#54]
1. Small bug: Paypal patron confirmation goes to 404 https://freesewing.org/undefined/patrons/thank-you
2.  FAQ in home page in footer

**Comment by joostdecock** [comment]
For 1) we first need to create the page https://freesewing.org/patrons/thank-you (it does not exist).
Then, we need to fix the links inhttps://github.com/freesewing/freesewing.org/blob/master/src/components/subscribe/PaypalButton.js

For 2) it can point to `/faq` as we have [a redirect](https://github.com/freesewing/freesewing.org/blob/master/gatsby-node.js#L7) for that to `/docs/about/faq`

Since 2) is very easy (and can be done through the GitHub interface, I'll create a new issue for that since it might be nice to leave that to a first-time contributor.

Adding a new page requires some more work, so we'll keep that here.

**Comment by joostdecock** [comment]
So the broken FAQ link is actually in the Footer component. Which means it's a different repo: This is actually in the Footer component. Closing in favor of https://github.com/freesewing/freesewing/issues/67
