### ISSUE TITLE
SSR issues in navbar and draft layout

### ISSUE THREAD

**Issue by Slylele** [freesewing/freesewing.org#658]
Not sure request must be submitted here but the links at the top right of the website have changed and seem inconsistent compared to previous version. 

- There is no more "Language" link/icon
- search icon is set for login
- login link (via search icon) propose to go to login page even if we are already connected..

![image](https://user-images.githubusercontent.com/57619777/79054638-e6cd7180-7c46-11ea-8d8e-9a311ef51119.png)

**Comment by Slylele** [comment]
I don't know if the issue below is linked to the same update, but page layout has changed too...

![image](https://user-images.githubusercontent.com/57619777/79054896-154c4c00-7c49-11ea-9728-a9aa5e9a6a64.png)

**Comment by joostdecock** [comment]
It's an SSR issue. I noticed it on the English website yesterday, and since you've got the same latest update, it's now on the French too. I haven't yet figured out what's causing it.

SSR = Server Side Render. Essentially, it means that the webpage you load initially, is different than the one loaded on the client.
You can check this by clicking to go to another page, then click to come back. The page should look fine. But when you reload it (so you get it from the server) it will be bad again.

These are not so easy to fix, but I will see what I can do :)

**Comment by joostdecock** [comment]
This is fixed now. Thanks again for reporting it.
