### ISSUE TITLE
Pattern Drafting (Theo)

### ISSUE THREAD

**Issue by GitBen2** [freesewing/freesewing.org#67]
Theo: The pattern options are appearing as node variables. 
Also, there are a number of orphaned alignment spots.

**Comment by joostdecock** [comment]
Thanks for reporting these @GitBen2 you're doing great work :)

Just to be clear, when you say *appear as node variables*, you mean this?
![Screenshot_2019-08-27 Choose a model](https://user-images.githubusercontent.com/1708494/63779617-237e6f80-c8e7-11e9-97ae-8a91b80a5960.png)

And when you say *orphaned alignment spots* you mean these notches that shouldn't be there?  
![Screenshot_2019-08-27 Choose a model(1)](https://user-images.githubusercontent.com/1708494/63779766-62142a00-c8e7-11e9-9c6a-df76cd3df409.png)

**Comment by GitBen2** [comment]
Yes to both.

By the way, I think that the freesewing concept is truly superb, thank you for the effort!

**Comment by joostdecock** [comment]
Thank you :)

The orphaned snippets have been fixed. But it's in our pattern code, so it won't show up until we roll out 2.0.1. I hope to be able to do it tonight, if not, probably tomorrow.

I'll keep this open until then.


The *node variables* you see is because those options haven't been translated yet. Another reason to keep this open.

**Comment by joostdecock** [comment]
2.0.1 has been deployed, the snippets issue is gone.
I'm closing this new, for the translation issues, I've created https://github.com/freesewing/freesewing/issues/90
