### ISSUE TITLE
Neck circumference not saving from blank slate modal

### ISSUE THREAD

**Issue by kieranklaassen** [freesewing/freesewing.org#68]
https://www.loom.com/share/40e5dbc9ded54c4ab8d5cb5a825910f5

**Comment by joostdecock** [comment]
I stumbled on this myself today, and fixed it. But I didn't realize it was this issue.

It was actually just a broken link in the 'start with neck circumference' button. It linked to 'neckcircumference' rather than 'neckCircumference` (notice the capital C).
The measurement is taken from the URL, and everything seems to work, but you can't save it because the backend won't accept a non-existing measurement.

Anyway, it's fixed and I'll be rolling out this fix later tonight (I hope)
