### ISSUE TITLE
Simone shirt - n[k].rotate is not a function

### ISSUE THREAD

**Issue by fizeelacks** [freesewing/freesewing.org#740]
Hello whomever it may concern, I shall open yet another issue on the Simone shirt - unfortunately, the other issues with n[k].rotate were closed due to lack of information.

Username is fizzylegs and the shirt is for Alex.

I double-checked and retook the measurements [ETA: rounded the measurements up/down to avoid decimal points] to make sure that wasn't the problem, but I'm still getting the error.

Stack trace

1/vG/Be.prototype.draftFbaFront@https://en.freesewing.org/4d90dbe830f6af6b1b9b218343a74e4baa7daf3e-33b47ce430fd4a24fb06.js:1:358058
AxEy/V.prototype.draft@https://en.freesewing.org/4d90dbe830f6af6b1b9b218343a74e4baa7daf3e-33b47ce430fd4a24fb06.js:1:647011
rlTK/t.a@https://en.freesewing.org/a550341fd3272bdc56bf5664c5e7ad30c4db79b0-fef43aab2b28396f3040.js:1:50395
Ki@https://en.freesewing.org/framework-659bfc594c4e339207ea.js:1:70018
Fa@https://en.freesewing.org/framework-659bfc594c4e339207ea.js:1:78879
vo@https://en.freesewing.org/framework-659bfc594c4e339207ea.js:1:117482
cu@https://en.freesewing.org/framework-659bfc594c4e339207ea.js:1:108807
ou@https://en.freesewing.org/framework-659bfc594c4e339207ea.js:1:108730
Zo@https://en.freesewing.org/framework-659bfc594c4e339207ea.js:1:105760
Hl/<@https://en.freesewing.org/framework-659bfc594c4e339207ea.js:1:57402
KqkS/t.unstable_runWithPriority@https://en.freesewing.org/framework-659bfc594c4e339207ea.js:1:4696
jl@https://en.freesewing.org/framework-659bfc594c4e339207ea.js:1:57111
Hl@https://en.freesewing.org/framework-659bfc594c4e339207ea.js:1:57349
Bl@https://en.freesewing.org/framework-659bfc594c4e339207ea.js:1:57282
vu@https://en.freesewing.org/framework-659bfc594c4e339207ea.js:1:114488
KqkS/t.unstable_runWithPriority@https://en.freesewing.org/framework-659bfc594c4e339207ea.js:1:4696
jl@https://en.freesewing.org/framework-659bfc594c4e339207ea.js:1:57111
hu@https://en.freesewing.org/framework-659bfc594c4e339207ea.js:1:114140
mu/<@https://en.freesewing.org/framework-659bfc594c4e339207ea.js:1:114051
U@https://en.freesewing.org/framework-659bfc594c4e339207ea.js:1:3636
KqkS/T.port1.onmessage@https://en.freesewing.org/framework-659bfc594c4e339207ea.js:1:2392

**Comment by joostdecock** [comment]
Thank you for reporting this @fizeelacks and sharing the info required to reproduce it. I will try to have a look at this tonight.

**Comment by joostdecock** [comment]
I had a quick look, and the problem is the shoulder slope measurement. You have it at 45cm (for Alex), but that would make the shoulder very very sloped and is probably incorrect since your HPS to hips back is 51cm.  
When I change the shoulder slope measurement to 50cm, Simone drafts fine.

Now the real problem here is that it is difficult to accurately measure the shoulder slope. Which is why we're changing it in 2.7.0 which should be out sometime in July.

At that time, we'll ask you to input your shoulder slope in degrees, which should be a lot more intuitive. Until that time, you can increase the shoulder slope measurement on Alex, and it should be fine.
